info:
  contact: {}
paths:
  /blobs/{url}:
    get:
      parameters:
      - description: The URL of the blob
        in: path
        name: url
        required: true
        type: string
      responses:
        "200":
          description: The blob content
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
      summary: Get a blob by URL
swagger: "2.0"
